### PR TITLE
make bitextor-warc2preprocess.py more robust to internet archive warc

### PR DESCRIPTION
**Pull request by PinzhenChen**
I am not very familiar with the warc2preprocess.py code. Is line 121 used to remove the HTTP return code (e.g. b'HTTP/1.1 403 Forbidden') from the payload, since the index() method only finds the first occurrence of the matched string?

If so, I did a simple fix yesterday. However, that was not 100% correct because today I came across some Warc records that contain neither "\r\n\r\n" nor "\r\n\n". Do you think the updated if-else will catch all the conditions?

Thanks!

### CODE REVIEW

**Comment by lpla** [comment]
With line 121 we obtain the actual content of the document without response data (and return code), in case this data exist. Response data and the document is separated by "\r\n\r\n" in wget WARCs, but I think the WARC standard draft doesn't specify this. Bitextor is tested with wget WARCs and other WARCs without response or HTTP codes (line 119).

So, if you could share a WARC document that has problems with this, I could take a look before merging this code and support this WARC variant once I fully understand its format.

**Comment by PinzhenChen** [comment]
Thank you for the clarification! I guess I misunderstood the code to some extent.

I was running warc2preprocess.py on Internet Archive's `SURV-20141216175545-crawl420/SURV-20141216181500-00001.warc.gz`

Command: `gzip -dc /directory_to_folder/SURV-20141216175545-crawl420/SURV-20141216181500-00001.warc.gz | python bitextor/bitextor-warc2preprocess.py --verbose --output-dir out/ &> log &`

I added a `print(payload)` statement and I was able to see:
1. Expected "\r\n\r\n":

> b'HTTP/1.1 200 OK\r\nDate: ...... **\r\n\r\n** <!DOCTYPE html PUBLIC......

2.  Some only contain response with no content, so original code throws ValueError :

> b'HTTP/1.1 301 Found\nLocation: http://angelpie.eu\nConnection: close\r\n\n'

So I guess we can trim at `index("\r\n\n")+1`

3. However, some other payloads does not contain any of the above:

> b'20141216181500\nanythingbutweddings.com.\t600\tIN\tA\t97.74.42.79\n'

Thanks,
Patrick

**Comment by lpla** [comment]
I see. So, as I guessed, there is no standard in how integrating HTTP response message and actual payload. This is going to be a bit tricky and hacky, but let me rewrite those replacements a bit to avoid unexpected behaviors.

**Comment by lpla** [comment]
I tested my changes with the same file you were using, but I didn't wait until it finished because it is quite big. Please, tell me if you see any other case or if my changes breaks anything.

I will merge once you confirm is all right on your side.

**Comment by PinzhenChen** [comment]
Strangely the new script always "freezes" at a certain record. No error, no exception, no logging, and the programme does not crash... 

______________
I rolled back to the original version and added a try-catch statement, as shown below, the script worked fine. Hence i guess the code change introduced some unexpected behaviour.

```
if payload.lstrip()[0:7] == b"HTTP/1.":
     try:
            payload=payload[payload.index(b"\r\n\r\n")+4:]
        except ValueError:
            pass
    ........
```

I got a new error with the above code (because the script was never able to reach this far before) this time:

```
for record in f:
  File "/mnt/buri0/shared/patrickchen/venv/lib/python3.5/site-packages/warc/warc.py", line 412, in __iter__
    record = self.read_record()
  File "/mnt/buri0/shared/patrickchen/venv/lib/python3.5/site-packages/warc/warc.py", line 389, in read_record
    self.finish_reading_current_record()
  File "/mnt/buri0/shared/patrickchen/venv/lib/python3.5/site-packages/warc/warc.py", line 385, in finish_reading_current_record
    self.expect(self.current_payload.fileobj, "\r\n")
  File "/mnt/buri0/shared/patrickchen/venv/lib/python3.5/site-packages/warc/warc.py", line 377, in expect
    raise IOError(message)
OSError: Expected '\r\n', found 'WARC/1.0\r\n'
```

exactly same as:
https://github.com/commoncrawl/news-crawl/issues/11#issue-182767644

Someone proposed to add a wrapper outside `for record in f` to handle it.

Thanks!

**Comment by lpla** [comment]
> Strangely the new script always "freezes" at a certain record. No error, no exception, no logging, and the programme does not crash...
> 

Do you have the document URI from verbose/logging output at which the script get stuck? I would like to fix this bug properly and making WARC reading as much "format-proof" as possible instead of ignoring problematic documents.

> I rolled back to the original version and added a try-catch statement, as shown below, the script worked fine. Hence i guess the code change introduced some unexpected behaviour.
> 
> ```
> if payload.lstrip()[0:7] == b"HTTP/1.":
>      try:
>             payload=payload[payload.index(b"\r\n\r\n")+4:]
>         except ValueError:
>             pass
>     ........
> ```
> 
> I got a new error with the above code (because the script was never able to reach this far before) this time:
> 
> ```
> for record in f:
>   File "/mnt/buri0/shared/patrickchen/venv/lib/python3.5/site-packages/warc/warc.py", line 412, in __iter__
>     record = self.read_record()
>   File "/mnt/buri0/shared/patrickchen/venv/lib/python3.5/site-packages/warc/warc.py", line 389, in read_record
>     self.finish_reading_current_record()
>   File "/mnt/buri0/shared/patrickchen/venv/lib/python3.5/site-packages/warc/warc.py", line 385, in finish_reading_current_record
>     self.expect(self.current_payload.fileobj, "\r\n")
>   File "/mnt/buri0/shared/patrickchen/venv/lib/python3.5/site-packages/warc/warc.py", line 377, in expect
>     raise IOError(message)
> OSError: Expected '\r\n', found 'WARC/1.0\r\n'
> ```
> 
> exactly same as:
> [commoncrawl/news-crawl#11 (comment)](https://github.com/commoncrawl/news-crawl/issues/11#issue-182767644)
> 
> Someone proposed to add a wrapper outside `for record in f` to handle it.
> 
> Thanks!

Ignoring problematic documents is an alternative solution, that's right, but I would like to extract as many information as possible.

But this new error means that the WARC file is badly formed, because of the end of a document. In the standard draft it is mandatory that each WARC document is separated by '\r\n' before WARC/1.0 and after the specified Content-lenght amount of data (that's why the error is `OSError: Expected '\r\n', found 'WARC/1.0\r\n'`). So if two documents are not well separated, `warc` library crashes.

I think we cannot manage it outside the for loop right now because this error only happens when the BufferedReader in `warc` library doesn't manage to read correctly a document. Unless we read the WARC document twice (one to check/fix WARC errors and then the usual document processing), which is very inefficient.

Maybe we should switch to [`warcio`](https://github.com/webrecorder/warcio) library instead of using the Internet Archive `warc` one, as [in your quoted issue they say it is more reliable](https://github.com/commoncrawl/news-crawl/issues/11#issuecomment-331382913). Also, the main issue there [was fixed by fixing the WARC files, not code](https://github.com/commoncrawl/news-crawl/issues/11#issuecomment-332130665).

So let's fix this issue first and then fix the stuck one. I am going to revert my changes and use your `try: ... except: pass` and replace `warc` with `warcio`. It could take me some time as the interface is quite different.

Meanwhile, the only thing we could try is to fix WARC files the same way CommonCrawl people did.

**Comment by PinzhenChen** [comment]
Thanks for getting back. I agree with fixing `OSError` first by changing to `warcio`.

I am looking at the "stuck" problem. Unfortunately, some machines are down today so I cannot access `SURV-20141216175545-crawl420/SURV-20141216181500-00001.warc.gz`. I am testing on `SURV-20141218224923-crawl339/SURV-20141218224923-00050.warc.gz` instead.

Anyway, regarding the inaccessible `SURV-20141216175545-crawl420/SURV-20141216181500-00001.warc.gz`, the last 10 lines of the log is here: [log.txt](https://github.com/bitextor/bitextor/files/3276176/log.txt). I had a `print(payload)` before your regular expression, so I think the script stuck between processing the last payload and logging the next record/URI.

**Comment by PinzhenChen** [comment]
Hi @lpla ,

Finally I was able to test on the original warc (`SURV-20141216175545-crawl420/SURV-20141216181500-00001.warc.gz`), and it looks like my 4-if-else commit https://github.com/bitextor/bitextor/pull/104/commits/66833b3c50f25764afae4e43885aeab357d0bcf4 worked fine (but still crashed on `OSError: Expected '\r\n', found 'WARC/1.0\r\n')`

This means that our logic was correct (or at least it improved over simply calling `index("\r\n\r\n")`). I looked up on the internet - regular expression in python can hang on large matches. Referring to the last line in the log file I uploaded in previous comment, I guess it was indeed the problem. Shall we use my commit https://github.com/bitextor/bitextor/pull/104/commits/66833b3c50f25764afae4e43885aeab357d0bcf4 maybe, and then we can look at warcio?

Thanks,
Patrick

**Comment by lpla** [comment]
I am finishing my tests with `warcio`. Yes, please, delete my latest commit on your branch/fork so it points to https://github.com/bitextor/bitextor/commit/66833b3c50f25764afae4e43885aeab357d0bcf4. But I will keep this pull request on hold because it is likely that `warcio` will fix both issues at the same time. I will comment here when I push my changes to bitextor:master, so you can test it too.

**Comment by lpla** [comment]
Please, test with latest Bitextor upstream master branch as I tested `warcio` and didn't see any regression. This library manages all WARC strange behaviors and formats we found in this pull request, so in case it works well for you too, we can discard this pull request code.

**Comment by PinzhenChen** [comment]
Thanks for coding things up.

The only thing is that I think `http_headers` should be `rec_headers` in line 130:
`if url[-4:] == ".pdf" or record.http_headers.get_header('Content-Type') == 'application/pdf'`
gives:
```
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    if url[-4:] == ".pdf" or record.http_headers.get_header('Content-Type') == 'application/pdf':
AttributeError: 'NoneType' object has no attribute 'get_header'
```

`if url[-4:] == ".pdf" or record.rec_headers.get_header('Content-Type') == 'application/pdf':`
works fine.

Other than this I believe that you can close the request.

**Comment by lpla** [comment]
> Thanks for coding things up.
> 
> The only thing is that I think `http_headers` should be `rec_headers` in line 130:
> `if url[-4:] == ".pdf" or record.http_headers.get_header('Content-Type') == 'application/pdf'`
> gives:
> 
> ```
> Traceback (most recent call last):
>   File "test.py", line 22, in <module>
>     if url[-4:] == ".pdf" or record.http_headers.get_header('Content-Type') == 'application/pdf':
> AttributeError: 'NoneType' object has no attribute 'get_header'
> ```
> 
> `if url[-4:] == ".pdf" or record.rec_headers.get_header('Content-Type') == 'application/pdf':`
> works fine. Pease refer to "files changed" tab.
> 

I wanted to detect PDFs by using Content Type MIME from HTTP headers now that `warcio` parses them, not using the Content Type in WARC header (which tend to be less precise or generic). But I should improve that code for strange cases with no HTTP response or any other field names. I just deleted that code for now.

> Other than this I believe that you can ~close the request~ maybe just merge since i changed it in my branch already.

Ok, I will merge now. Please, contact us if you find any other issue. Thank you!

**Pull request merged**
