### PR TITLE
Update dockerfile

### PR DESCRIPTION
**Pull request by zuny26**
Dockerfile now includes new dependencies and installation steps

### CODE REVIEW

**Review by lpla — APPROVED** [review]

**Comment by ZJaume** [comment]
Are the tests checking that Bicleaner is running succesfully with the default options? I don't see the `cmake` and `make` instructions for KenLM installation, only the Python packages (which is not enough).

**Comment by lpla** [comment]
Automatic tests pass and they include using a bicleaner model (not training one), and they passed. Why are `cmake` and `make` commands necessary instead of `python3.7 -m pip install https://github.com/kpu/kenlm/archive/master.zip --install-option="--max_order 7"`?

I knew this at some point, as I was the one that changed installation instructions in [bicleaner README.md](https://github.com/bitextor/bicleaner/commit/086df5f0f7bb2510d031a4694a19a94f5e5b3ca6), but we are using the pip command written in [Bitextor README.md](https://github.com/bitextor/bitextor#dependencies))

Did you (@ZJaume) face any issue regarding missing binaries by only using the pip command?

**Comment by ZJaume** [comment]
I was pointing out this because, a couple of weeks ago, one [issue](https://github.com/bitextor/bicleaner/issues/53) in Bicleaner was (probably) because of KenLM not correctly installed inside a Docker image. I supposed that that image is the Bitextor image because there is no Bicleaner Docker image. Furthermore, I've tried the `python3.7 -m pip install https://github.com/kpu/kenlm/archive/master.zip --install-option="--max_order 7"` command inside a virtual environment and, after that, KenLM commands are not available in the command line, which are the ones that Bicleaner uses.

**Comment by lpla** [comment]
Yeah, you are right. It seems like we didn't got this issue because we didn't train a model with features that needed calling `lmplz` binary, and installing `kenlm` with `pip` only works to run the classifier, which was the main use of Bicleaner in Bitextor. We will use the installation steps written en Bicleaner README.md before merging this pull request.

Thank you for taking a look!

**Pull request merged**
