### PR TITLE
Bitextor.faz

### PR DESCRIPTION
**Pull request by kirefu**
Hi,

I've submitted several changes

Added cache capabilities to bicleaner rules: 
- no longer computing score multiple times for same sentence pair
- bicleaner/bicleaner_classifier_lite.py also updated to output score_only

Added parallel capabilities to bicleaner and translate rules:

 - this is wrapped by cache.
- When running in cluster mode, cluster.json file must include a cpus-per-task parameter for parallel to work.
- new boolean config options: parallelTranslate, parallelBicleaner
- new integer config options: parallelBlock, parallelMemfree

Merged rules bicleaner filter and elrc to just one rule:

- replaced bitextor-filterbicleaner.py with an awk command

Added early stopping:

- rule docalign_extracted (no more docaling!) first checks whether lang1 and lang2 are both in the lang.xz file, and if not, creates empty output files.
- translation rules also check if input is non empty, otherwise automatically generate empty output
- this could be recursively implemented, bu hopefully a nicer solution will be found.

Changes to deduped_tmx rule:

- Now automatically generates the corresponding deduped txt.gz file, along with the tmx.

I have tested that the changed rules work for the different scenarios, but of course may have missed a test case.

Best wishes,

Faheem

### CODE REVIEW

**Comment by mbanon** [comment]
Hey @lpla , @kirefu :
I have been reviewing changes in Snakemake, and, just to be sure: sharding/caching/deduping after bifixer/before bicleaner is not happening yet, is it?

**Comment by kirefu** [comment]
No it isn't, but these changes fix that (I did not implement any sharding as we are currently sharding by domain, so trying to shard within large domains only could get messy.

I also forgot to mention that we no longer need rule docalign_dedupe, as cache takes care of that for us.

**Comment by mbanon** [comment]
> @mbanon we still need that @kpu adds a `-k` option (like `sort -k`) to `cache` so we could use the `bifixer` hash. But we can accept this change meanwhile.

For sure! I was just wondering if it was already added :)

**Comment by lpla** [comment]
I have been reviewing the pull request and I will accept it when @mbanon releases Bicleaner 0.12, so the `--only-score` option does not break Bitextor workflow. Also, that give us time to integrate all our dev branches we are finishing and test merges properly.

**Comment by lpla** [comment]
This pull request has been re-implemented in `bitextor.faz` branch, given latest changes that have been done in Bitextor. All features but bicleaner+elrc rules merge have been coded. I am closing this pull request and creating a new one with the new code.

**Pull request closed without merging**
